config/routes.rb
Rails.application.routes.draw do


  resources :store_owners
  resources :payments, only: [:new, :create]
  resources :charges, only: [:new, :create]
  resources :product_comments
  resources :comments
  resources :product_attachments
  resources :post_attachments
  resources :categories
  resources :pages
  resources :password_resets


  get 'pages/index'

  get 'pages/show'

  resources :posts do
    resources :comments
  end

  
  get 'admin' => 'admin#index'

resources :relationships, only: [:create, :destroy]

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end


  resources :users do
      get 'agreement'
      get 'store_owner'
  end


  resources :orders
  resources :carts
  get 'store/index'

  resources :line_items do
  	member do
  		get 'remove'
  		get 'add'
  	end
  end
  
  resources :products do
    get :who_bought, on: :member
    resources :product_comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	def add(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = line_items.build(product_id: product_id)
		end
		current_item
	end

	def remove(product_id)
		current_item = line_items.find_by_product_id(product_id)
		if current_item.quantity > 1
			current_item.quantity -= 1
		else
			current_item.destroy
		end
		current_item
	end
 
	def total_price
		line_items.to_a.sum{|item| item.total_price}
	end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_action :authorize
  
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
    redirect_to store_url, notice: 'Cannot access this page'
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = current_cart
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to acess invalid purchase list #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html
        format.json{render json: @cart}
      end
    end
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Purchase list was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Purchase list was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil
    
    respond_to do |format|
      format.html { redirect_to :back, notice: 'Purchase list was successfully deleted.'}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = current_cart
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<%= stylesheet_link_tag "carts", :media => "all" %>
<div class="container containerMob">
	<div id="paddingCart">
		<div class="text-center">
			<div class="cart_title"><p id="inCartFont">Purchase List</p></div>
		</div>
		<hr>
			<table class="cartTable">
				<%= render(@cart.line_items) %>
				
				<tr class="total_line">
					<th></th>
         			<th class="second"></th>
					<td class="total_cell">Total</td>
					<td class="total_cell"><%= number_to_currency(cart.total_price) %></td>
				</tr>
			</table>
			<hr>
			<div class="text-center">
				<div class="row">
					<div class="col-md-12">
						<div class="col-md-6">
							<%= button_to "Checkout", new_order_path, method: :get, class: "buttonCheck buttonCheckIn" %>
						</div>
						<div class="col-md-6">
							<%= button_to "Empty List", cart, method: :delete, confirm: "Are you sure?", class: "buttonEmp buttonEmpIn" %>
						</div>
					</div>
				</div> 
			</div>    
		</div>
</div>

app/views/carts/_form.html.erb
<%= form_for(cart) do |f| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<div class="text-center">
<h1>Editing Cart</h1>
</div>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cart', new_cart_path %>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<%= stylesheet_link_tag "carts", :media => "all" %>
<div class="container">
	<div class="text-center">
	<% if notice %>
		<p id="notice"><%= notice %></p>
	<% end %>
		<div class="mainTitle">Purchase List</div>
      	<hr>

      	<% if @cart.line_items.present? %>
		<table class="table table-bordered">
			<thead>
      			<tr>
        			<th>Quantity</th>
			        <th>Product name</th>
			        <th class="pageName">Store name</th>
			        <th>Price</th>
      			</tr>
   		 	</thead>
   		 	<tbody>
				<%= render(@cart.line_items) %>
			<th></th>
         	<th class="second"></th>
				<td >Total</td>
				<td class="total_cell"><%= number_to_currency(@cart.total_price) %></td>
			</tbody>
		</table>

		<div class="col-md-3 col-md-offset-3">
			<%= button_to "Checkout", new_order_path, method: :get, class: "button buttonG center-block btn-responsive" %>
		</div>
		<div class="col-md-3">
			<%= button_to "Empty Purchase List", @cart, method: :delete, confirm: "Are you sure?", class: "button buttonR center-block btn-responsive" %>
		</div>
		<% else %>
			<p class="pNoCart">There are no items in your purchase list. Click on the button to look at the products to add to your purchase list.</p>
			<%= button_to "To Products", products_path, method: :get, class: "newCart" %>
		<% end %>
	</div>
</div>