config/routes.rb
Rails.application.routes.draw do


  resources :store_owners
  resources :payments, only: [:new, :create]
  resources :charges, only: [:new, :create]
  resources :product_comments
  resources :comments
  resources :product_attachments
  resources :post_attachments
  resources :categories
  resources :pages
  resources :password_resets


  get 'pages/index'

  get 'pages/show'

  resources :posts do
    resources :comments
  end

  
  get 'admin' => 'admin#index'

resources :relationships, only: [:create, :destroy]

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end


  resources :users do
      get 'agreement'
      get 'store_owner'
  end


  resources :orders
  resources :carts
  get 'store/index'

  resources :line_items do
  	member do
  		get 'remove'
  		get 'add'
  	end
  end
  
  resources :products do
    get :who_bought, on: :member
    resources :product_comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
end

app/models/post_attachment.rb
class PostAttachment < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :post
end

app/controllers/post_attachments_controller.rb
class PostAttachmentsController < ApplicationController
  before_action :authorize, except: [:show]
  before_action :set_post_attachment, only: [:show, :edit, :update, :destroy]

  # GET /post_attachments
  # GET /post_attachments.json
  def index
    @post_attachments = PostAttachment.all
    @cart = current_cart
    redirect_to store_url, notice: 'Cannot access this page'
  end

  # GET /post_attachments/1
  # GET /post_attachments/1.json
  def show
    @cart = current_cart
    @post = Post.find(params = @post_attachment.post_id)
    @post_attachments = @post.post_attachments
  end

  # GET /post_attachments/new
  def new
    @post = Post.find(params[:post_id])
    @post_attachment = PostAttachment.new
  end

  # GET /post_attachments/1/edit
  def edit
    redirect_to store_path, notice: "Image Cannot be edited."
  end

  # POST /post_attachments
  # POST /post_attachments.json
  def create
    @post_attachment = @post.post_attachments.build(post_attachment_params)
    @post = Post.find(params[:post_id])

    respond_to do |format|
      if @post_attachment.save
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully created.' }
        format.json { render :show, status: :created, location: @post_attachment }
      else
        format.html { render :new }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_attachments/1
  # PATCH/PUT /post_attachments/1.json
  def update
    respond_to do |format|
      if @post_attachment.update(post_attachment_params)
        format.html { redirect_to @post_attachment, notice: 'Post attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @post_attachment }
      else
        format.html { render :edit }
        format.json { render json: @post_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_attachments/1
  # DELETE /post_attachments/1.json
  def destroy
    @post_attachment.destroy
    respond_to do |format|
      format.html { redirect_to post_attachments_url, notice: 'Post attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_attachment
      @post_attachment = PostAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_attachment_params
      params.require(:post_attachment).permit(:post_id, :image)
    end
end

app/helpers/post_attachments_helper.rb
module PostAttachmentsHelper
end

app/views/post_attachments/_form.html.erb
<%= form_for(post_attachment) do |f| %>
  <% if post_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_attachment.errors.count, "error") %> prohibited this post_attachment from being saved:</h2>

      <ul>
      <% post_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :post_id %>
    <%= f.number_field :post_id %>
  </div>

  <%= image_tag @post_attachment.image %>
  <%= form_for(@post_attachment) do |f| %>
    <div class="field">
      <%= f.label :image %><br>
      <%= f.file_field :image %>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/post_attachments/edit.html.erb
<h1>Editing Post Attachment</h1>

<%= render 'form', post_attachment: @post_attachment %>

<%= link_to 'Show', @post_attachment %> |
<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Post</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_attachments.each do |post_attachment| %>
      <tr>
        <td><%= post_attachment.post_id %></td>
        <td><%= post_attachment.image %></td>
        <td><%= link_to 'Show', post_attachment %></td>
        <td><%= link_to 'Edit', edit_post_attachment_path(post_attachment) %></td>
        <td><%= link_to 'Destroy', post_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Attachment', new_post_attachment_path %>

app/views/post_attachments/new.html.erb
<h1>New Post Attachment</h1>

<%= render 'form', post_attachment: @post_attachment %>

<%= link_to 'Back', post_attachments_path %>

app/views/post_attachments/show.html.erb
<%= stylesheet_link_tag "post_attachments", :media => "all" %>
<p id="notice"><%= notice %></p>
<div class="container-fluid">
	<div class="text-center">
		  <div class="mainTitle"><%= @post_attachment.post.try :title %></div>
		  	<hr>
		<% if @post.post_attachments.length < 2 %>
			<% @post_attachments.each do |post_attachment| %>
				<%= image_tag(post_attachment.image, class: "postAttDispView") if post_attachment.image? %>
			<% end %>
		<% else %>
			<% @post_attachments.each do |post_attachment| %>
				<%= image_tag(post_attachment.image, class: "postAttDisp") if post_attachment.image? %>
			<% end %>
		<% end %>
	</div>
</div>