config/routes.rb
Rails.application.routes.draw do


  resources :store_owners
  resources :payments, only: [:new, :create]
  resources :charges, only: [:new, :create]
  resources :product_comments
  resources :comments
  resources :product_attachments
  resources :post_attachments
  resources :categories
  resources :pages
  resources :password_resets


  get 'pages/index'

  get 'pages/show'

  resources :posts do
    resources :comments
  end

  
  get 'admin' => 'admin#index'

resources :relationships, only: [:create, :destroy]

controller :sessions do
  get 'login' => :new
  post 'login' => :create
  delete 'logout' => :destroy
end


  resources :users do
      get 'agreement'
      get 'store_owner'
  end


  resources :orders
  resources :carts
  get 'store/index'

  resources :line_items do
  	member do
  		get 'remove'
  		get 'add'
  	end
  end
  
  resources :products do
    get :who_bought, on: :member
    resources :product_comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'store#index', as: 'store'
end

app/models/product_attachment.rb
class ProductAttachment < ApplicationRecord
	mount_uploader :image, ImageUploader
	belongs_to :product
end

app/controllers/product_attachments_controller.rb
class ProductAttachmentsController < ApplicationController
  before_action :authorize, except: [:index, :show]
  before_action :set_product_attachment, only: [:show, :edit, :update, :destroy]

  # GET /product_attachments
  # GET /product_attachments.json
  def index
    @product_attachments = ProductAttachment.all
    @cart = current_cart
    redirect_to store_url, notice: 'Cannot access this page'
  end

  # GET /product_attachments/1
  # GET /product_attachments/1.json
  def show
    @product = Product.find(params = @product_attachment.product_id)
    @cart = current_cart
    @product_attachments = @product.product_attachments.order("created_at DESC")
  end

  # GET /product_attachments/new
  def new
    @product_attachment = ProductAttachment.new
  end

  # GET /product_attachments/1/edit
  def edit
    redirect_to store_path, notice: "Image Cannot be edited."
  end

  # POST /product_attachments
  # POST /product_attachments.json
  def create
    @product_attachment = ProductAttachment.new(product_attachment_params)

    respond_to do |format|
      if @product_attachment.save
        format.html { redirect_to @product_attachment, notice: 'Product attachment was successfully created.' }
        format.json { render :show, status: :created, location: @product_attachment }
      else
        format.html { render :new }
        format.json { render json: @product_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_attachments/1
  # PATCH/PUT /product_attachments/1.json
  def update
    respond_to do |format|
      if @product_attachment.update(product_attachment_params)
        format.html { redirect_to @product_attachment, notice: 'Product attachment was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_attachment }
      else
        format.html { render :edit }
        format.json { render json: @product_attachment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_attachments/1
  # DELETE /product_attachments/1.json
  def destroy
    @product_attachment.destroy
    respond_to do |format|
      format.html { redirect_to product_attachments_url, notice: 'Product attachment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_attachment
      @product_attachment = ProductAttachment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_attachment_params
      params.require(:product_attachment).permit(:product_id, :image)
    end
end

app/helpers/product_attachments_helper.rb
module ProductAttachmentsHelper
end

app/views/product_attachments/_form.html.erb
<%= form_for(product_attachment) do |f| %>
  <% if product_attachment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_attachment.errors.count, "error") %> prohibited this product_attachment from being saved:</h2>

      <ul>
      <% product_attachment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %>
    <%= f.number_field :product_id %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_attachments/edit.html.erb
<h1>Editing Product Attachment</h1>

<%= render 'form', product_attachment: @product_attachment %>

<%= link_to 'Show', @product_attachment %> |
<%= link_to 'Back', product_attachments_path %>

app/views/product_attachments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Attachments</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_attachments.each do |product_attachment| %>
      <tr>
        <td><%= product_attachment.product_id %></td>
        <td><%= product_attachment.image %></td>
        <td><%= link_to 'Show', product_attachment %></td>
        <td><%= link_to 'Edit', edit_product_attachment_path(product_attachment) %></td>
        <td><%= link_to 'Destroy', product_attachment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Attachment', new_product_attachment_path %>

app/views/product_attachments/new.html.erb
<h1>New Product Attachment</h1>

<%= render 'form', product_attachment: @product_attachment %>

<%= link_to 'Back', product_attachments_path %>

app/views/product_attachments/show.html.erb
<%= stylesheet_link_tag "product_attachments", :media => "all" %>
<p id="notice"><%= notice %></p>

<div class="container-fluid">
	<div class="text-center">
		  <div class="mainTitle"><%= @product_attachment.product.try :title %></div>
		  	<hr>

		<% @product_attachments.reverse_each do |product_attachment| %>
			<%= image_tag(product_attachment.image.thumb, class: "productAttDisp") if product_attachment.image? %>
		<% end %>
	</div>
</div>